#!/usr/bin/env node
'use strict';

var fs = require('fs');
var utils = require('./lib/utils');
var mapview = require('./lib/mapview');
var argv = require('minimist')(process.argv.slice(2));

var electron = require('electron');
var app = electron.app;
var BrowserWindow = electron.BrowserWindow;
var log = require('electron-log');

var mbtiles = argv._;

var accessToken = argv.MapboxAccessToken ||
  process.env.MAPBOX_ACCESS_TOKEN ||
  process.env.MapboxAccessToken;

if (argv.version || argv.v) {
    return log.info(utils.version());
} else if (!mbtiles.length) {
    return log.info(utils.usage());
} else if (!accessToken) {
    throw (new Error('missing access token, try `export MAPBOX_ACCESS_TOKEN=...`'));
}

try {
    mbtiles.forEach(function (f) {
        fs.statSync(f).isFile();
    });
} catch (e) {
    return log.error(e);
}

var params = {
    mbtiles: mbtiles,
    port: argv.port || 20009,
    accessToken: accessToken
};

var mainWindow;

function createWindow() {
    mainWindow = new BrowserWindow({
        titleBarStyle: 'hidden'
    });

    mainWindow.loadURL('http://localhost:' + params.port + '/');

    // on window close throw everything away
    mainWindow.on('closed', function () {
        mainWindow = null;
    });
}

app.on('ready', createWindow);

app.on('window-all-closed', function () {
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

app.on('activate', function () {
    if (mainWindow === null) {
        createWindow();
    }
});

mapview.serve(params, function (err, config) {
    if (err) throw (new Error(err));
    log.info('Serving on http://localhost:' + config.port);
});
